

GET http://localhost:3000/data/users

###

POST http://localhost:3000/data/users/signup
Content-Type: application/json

{
    "userId": 43,
    "password": "43"
}

###

POST http://localhost:3000/data/users/login
Content-Type: application/json

{
    "userId": 64,
    "password": "64"
}

###

GET http://localhost:3000/data/todos/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTU3NzI4OTM2OX0.JaUnoL6BmmsIPxTXTuw6yPWshI4bF9flK3QaByUBaqY 
###

GET http://localhost:3000/data/todos/5e03892e70faf608d8ec7418

###

POST http://localhost:3000/data/todos
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTU3NzI4OTM2OX0.JaUnoL6BmmsIPxTXTuw6yPWshI4bF9flK3QaByUBaqY
Content-Type: application/json

{
    "userId": 4,
    "title": "password is too easy to guess"
}

###

PUT http://localhost:3000/data/todos/5e03892e70faf608d8ec7418